// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20220920064106_AddDataSeeding")]
    partial class AddDataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ParentId");

                    b.ToTable("Comments");

                    b.HasCheckConstraint("CK_Comment_ParentId", "[ParentId] != [Id]");
                });

            modelBuilder.Entity("Data.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Data.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Name", "ParentId")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasCheckConstraint("CK_Genre_ParentId", "[ParentId] != [Id]");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47caa6af-167e-46b5-adbe-ee93534885b0"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("00c08f06-efcd-41d3-9621-5b1e90d2da6c"),
                            Name = "RTS",
                            ParentId = new Guid("47caa6af-167e-46b5-adbe-ee93534885b0")
                        },
                        new
                        {
                            Id = new Guid("54f35383-8f67-4481-a559-1c01e697be33"),
                            Name = "TBS",
                            ParentId = new Guid("47caa6af-167e-46b5-adbe-ee93534885b0")
                        },
                        new
                        {
                            Id = new Guid("db7653d5-b4be-40e1-9985-6a4a61a674ed"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("3db87e8a-9714-4e27-bba7-bbafa6bae2b9"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("98047c28-741b-4add-be6d-e46d81e9bb45"),
                            Name = "Races"
                        },
                        new
                        {
                            Id = new Guid("f6de1593-a8ee-45d5-b220-57a1da6f566e"),
                            Name = "Rally",
                            ParentId = new Guid("98047c28-741b-4add-be6d-e46d81e9bb45")
                        },
                        new
                        {
                            Id = new Guid("6519ec12-d1fd-49d5-81b2-8f5545390b9d"),
                            Name = "Arcade",
                            ParentId = new Guid("98047c28-741b-4add-be6d-e46d81e9bb45")
                        },
                        new
                        {
                            Id = new Guid("30d7e62c-13ce-4d3f-9590-339c9d9ecf06"),
                            Name = "Formula",
                            ParentId = new Guid("98047c28-741b-4add-be6d-e46d81e9bb45")
                        },
                        new
                        {
                            Id = new Guid("0bd3d31b-65b6-47cd-adad-a8a90618c2ac"),
                            Name = "Off-road",
                            ParentId = new Guid("98047c28-741b-4add-be6d-e46d81e9bb45")
                        },
                        new
                        {
                            Id = new Guid("2a1dc5b7-373e-4da3-bd8c-caa3158888f7"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("7607b9a4-d7ce-46ef-a67c-884ec3b3ac1f"),
                            Name = "FPS",
                            ParentId = new Guid("2a1dc5b7-373e-4da3-bd8c-caa3158888f7")
                        },
                        new
                        {
                            Id = new Guid("54f3b304-1535-418e-bbf0-2e8a4028c371"),
                            Name = "TPS",
                            ParentId = new Guid("2a1dc5b7-373e-4da3-bd8c-caa3158888f7")
                        },
                        new
                        {
                            Id = new Guid("7707e09b-6f55-4eaa-bcab-ae1491bbb0db"),
                            Name = "Misc.",
                            ParentId = new Guid("2a1dc5b7-373e-4da3-bd8c-caa3158888f7")
                        },
                        new
                        {
                            Id = new Guid("a13f2dfc-d2c3-4122-ade7-9a4c44915ada"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("8df84e6c-bbf3-4b77-bf8d-04878eeddc15"),
                            Name = "Puzzle & Skill"
                        },
                        new
                        {
                            Id = new Guid("9e8cb492-4345-43ba-9050-dbdf34156713"),
                            Name = "Misc."
                        });
                });

            modelBuilder.Entity("Data.Entities.PlatformType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("PlatformTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54a66d4a-bd5d-4bf0-ad27-a5eb6584c512"),
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("fddef9fc-211c-403f-ab7e-a10be5f180c4"),
                            Type = "Browser"
                        },
                        new
                        {
                            Id = new Guid("397f9580-8b09-43ea-a9de-07e9b78422f9"),
                            Type = "Desktop"
                        },
                        new
                        {
                            Id = new Guid("ce56abee-2346-46e6-a683-7697dcbeef2b"),
                            Type = "Console"
                        });
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.Property<Guid>("GamesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenresId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GamesId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("GameGenre");
                });

            modelBuilder.Entity("GamePlatformType", b =>
                {
                    b.Property<Guid>("GamesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlatformTypesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GamesId", "PlatformTypesId");

                    b.HasIndex("PlatformTypesId");

                    b.ToTable("GamePlatformType");
                });

            modelBuilder.Entity("Data.Entities.Comment", b =>
                {
                    b.HasOne("Data.Entities.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Comment", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Game");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Data.Entities.Genre", b =>
                {
                    b.HasOne("Data.Entities.Genre", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.HasOne("Data.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamePlatformType", b =>
                {
                    b.HasOne("Data.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.PlatformType", null)
                        .WithMany()
                        .HasForeignKey("PlatformTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.Game", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
